# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Wyn Nelson
title: Wyn Nelson
email: wynlnelson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   Wyn Nelson is a teaching graduate student that applies UX design principles to the way she teaches. She recieved her bachelor's degree in math with a minor in computer science in 2016 and her master's in math in 2018.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

minima:
# generate social links in footer
  social_links:
    linkedin: wynnelson
    github:   wynnelson


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Google Analytics
google_analytics: UA-164343861-1


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
